# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- AltoroJ-3.2

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    curl -v -k -X POST --header 'Content-Type:application/json' --header 'Accept:application/json' -d '{"KeyId":"'"local_809e4431-80b4-e2b0-4e1c-6e70e9c96ab8"'","KeySecret":"'"RTVLNg4yDM44ef6meft6YMYdOAH8z15EcMmZ5NQX5FLI"'"}' "https://as.botexam.net/api/v4/Account/ApiKeyLogin"
    echo See https://aka.ms/yaml
  displayName: 'AS360 API login'
